<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="6" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62183" started-at="2018-05-31T09:31:40Z" finished-at="2018-05-31T09:32:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62183" started-at="2018-05-31T09:31:40Z" finished-at="2018-05-31T09:32:43Z">
      <class name="Zmartasweden.Zmartasweden.Zmarta_se">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="beforeTest" is-config="true" duration-ms="61352" started-at="2018-05-31T15:01:40Z" finished-at="2018-05-31T15:02:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="VerifyPageTitle()[pri:0, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyPageTitle" duration-ms="297" started-at="2018-05-31T15:02:42Z" description="This Test Case is to Verify the Landing page of the Website" finished-at="2018-05-31T15:02:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyPageTitle -->
        <test-method status="FAIL" signature="VerifyLoan()[pri:1, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyLoan" duration-ms="82" started-at="2018-05-31T15:02:42Z" description=" This Test Case  is to Verify the Applicant Loan Information" depends-on-methods="Zmartasweden.Zmartasweden.Zmarta_se.VerifyPageTitle" finished-at="2018-05-31T15:02:42Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"id","selector":"privateLoanTeaserButton"}  (Session info: chrome=66.0.3359.181)  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 37 millisecondsFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.htmlBuild info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'System info: host: 'LAPTOP-L45CF4AI', ip: '172.16.16.91', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'Driver info: org.openqa.selenium.chrome.ChromeDriverCapabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Jino\AppData\Local\Temp\scoped_dir14800_17260}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.181, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]Session ID: 059db2024a625c6cf1689e86fe8a93ea]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"privateLoanTeaserButton"}  (Session info: chrome=66.0.3359.181)  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 37 millisecondsFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.htmlBuild info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'System info: host: 'LAPTOP-L45CF4AI', ip: '172.16.16.91', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'Driver info: org.openqa.selenium.chrome.ChromeDriverCapabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Jino\AppData\Local\Temp\scoped_dir14800_17260}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.181, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]Session ID: 059db2024a625c6cf1689e86fe8a93eaat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)at java.lang.reflect.Constructor.newInstance(Unknown Source)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:393)at org.openqa.selenium.By$ById.findElement(By.java:214)at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)at Pageobject.Locators.ApplyLoan(Locators.java:142)at Zmartasweden.Zmartasweden.Zmarta_se.VerifyLoan(Zmarta_se.java:86)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoan -->
        <test-method status="SKIP" signature="VerifyPersonalInfo()[pri:2, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyPersonalInfo" duration-ms="0" started-at="2018-05-31T15:02:42Z" description=" This Test Case   is to Verify the Applicant Personal Information " depends-on-methods="Zmartasweden.Zmartasweden.Zmarta_se.VerifyLoan" finished-at="2018-05-31T15:02:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Zmarta_se.VerifyPersonalInfo()[pri:2, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Zmarta_se.VerifyPersonalInfo()[pri:2, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyPersonalInfo -->
        <test-method status="SKIP" signature="VerifyMaritalstatus()[pri:3, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyMaritalstatus" duration-ms="0" started-at="2018-05-31T15:02:42Z" description="  This Test Case is to Verify  the Applicant  Marital status " depends-on-methods="Zmartasweden.Zmartasweden.Zmarta_se.VerifyPersonalInfo" finished-at="2018-05-31T15:02:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Zmarta_se.VerifyMaritalstatus()[pri:3, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Zmarta_se.VerifyMaritalstatus()[pri:3, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyMaritalstatus -->
        <test-method status="SKIP" signature="VerifyEmploymentInfo()[pri:4, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyEmploymentInfo" duration-ms="0" started-at="2018-05-31T15:02:42Z" description="This Test Case is to Verify the Applicant Employment Information" depends-on-methods="Zmartasweden.Zmartasweden.Zmarta_se.VerifyMaritalstatus" finished-at="2018-05-31T15:02:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Zmarta_se.VerifyEmploymentInfo()[pri:4, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Zmarta_se.VerifyEmploymentInfo()[pri:4, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyEmploymentInfo -->
        <test-method status="SKIP" signature="VerifyFinalLoan()[pri:5, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="VerifyFinalLoan" duration-ms="0" started-at="2018-05-31T15:02:42Z" description="This Test Case is to  Verify  the Applicant Final Loan Information" depends-on-methods="Zmartasweden.Zmartasweden.Zmarta_se.VerifyEmploymentInfo" finished-at="2018-05-31T15:02:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Zmarta_se.VerifyFinalLoan()[pri:5, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Zmarta_se.VerifyFinalLoan()[pri:5, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyFinalLoan -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Zmartasweden.Zmartasweden.Zmarta_se@37ceb1df]" name="afterTest" is-config="true" duration-ms="187" started-at="2018-05-31T15:02:42Z" finished-at="2018-05-31T15:02:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Zmartasweden.Zmartasweden.Zmarta_se -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
